//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product2
    {
        public int id { get; set; }
        public string proname { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<decimal> quntity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Brand3 Brand3 { get; set; }
        public virtual category category { get; set; }
    }
}
